### ISSUE TITLE
PyPi needs an M1 build for Mac

### ISSUE THREAD

**Issue by jacobwilliams** [gnikit/findent-pypi#13]
i.e, `macosx_arm64`. Otherwise, it doesn't work on a recent Mac with Apple Silicon processor.

**Comment by gnikit** [comment]
Thanks @jacobwilliams for the heads up. I actually went ahead and rewrote the entire `setup.py` to use `python -m build`, which would solve this issue too but for some reason I couldn't get it to work. I will have another go

**Comment by gnikit** [comment]
I don't think I will be able to make this happen since GitHub does not support M1 (or now M2) silicon https://github.com/actions/virtual-environments/issues/2187 and I am not sure what the alternatives are

**Comment by minhqdao** [comment]
Seems like there was [an update](https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/). There is still the remaining `setup-python` issue, but technically we aren't using it. 🤔
